"""empty message

Revision ID: 771d156267f8
Revises: f7f16e0d012d
Create Date: 2019-06-06 22:05:34.884257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771d156267f8'
down_revision = 'f7f16e0d012d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['uid'])
    op.drop_column('users', 'pin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###
